from __future__ import annotations

from typing import Any, Protocol


class AdminApplication(Protocol):
    cookie_name: str
    cookie_secure: bool
    cookie_max_age: int
    max_upload_bytes: int

    def login(self, username: str, password: str) -> Any: ...

    def current_session(self, token: str) -> Any: ...

    def logout(self, token: str) -> None: ...

    def upload_document(self, **kwargs: Any) -> Any: ...

    def list_documents(self, *, limit: int, offset: int) -> Any: ...

    def get_document(self, document_id: str) -> Any: ...

    def get_ingestion_job(self, job_id: str) -> Any: ...

    def retry_ingestion_job(self, job_id: str) -> Any: ...

    def cancel_ingestion_job(self, job_id: str) -> Any: ...

    def create_evaluation(self, *, name: str, suite: str, requested_by_id: str) -> Any: ...

    def list_evaluations(self, *, limit: int, offset: int) -> Any: ...

    def get_evaluation(self, job_id: str) -> Any: ...

    def evaluation_summary(self) -> Any: ...
